name: Greetings for PR Contributors

on:
  pull_request:
    branches:
      - master

jobs:
  test_job:
    name: Running Unit Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: '3.7' 
        pr-message: 'Thanks for your contribution'' first pr'
    - name: Run Tests
      run: python -m unittest
