name: Greetings for PR Contributors

on: [pull_request]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        pr-message: 'Message that will be displayed on users'' first pr'
    - name:
      run: |
        python -m unittest
