name: Run Unit Tests
on: pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare repo
        uses: actions/checkout@master
      - name: Test
        uses: onichandame/python-test-action@master
        working-directory: ./tests
        with:
          path: 'first_repo/tests'
          deps_list: 'requirement'
